feat: testing pre commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,6 +1,21 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-# Run lint-staged or other tasks
+# Get the list of staged files
+staged_files=$(git diff --staged --name-only)
+
+# Define the allowed folders and files
+allowed_folders=("serverless")
+allowed_files=("pnpm-workspace.yaml")
+
+# Check if any staged files are not in the allowed folders or files
+for file in $staged_files; do
+    if [ ! -z "$(echo "${allowed_folders[@]}" | grep -o "$file")" ] || [ ! -z "$(echo "${allowed_files[@]}" | grep -o "$file")" ]; then
+        echo "Error: You can only commit changes from the 'serverless' folder or 'pnpm-workspace.yaml'."
+        exit 1
+    fi
+done
+
+# If all checks pass, run lint-staged or other tasks
 npx --no-install lint-staged # prevents installing lint-staged globally instead it runs it temporarily for this script execution.
 pnpm run lint
